sources:

  - name: User
    handler:
      grpc:
        endpoint: "localhost:50051"
        protoFile: "./proto/user.proto"
        packageName: "user"
        serviceName: "UserService"
        useHTTPS: false

  - name: Auth
    handler:
      grpc:
        endpoint: "localhost:50051"
        protoFile: "./proto/auth.proto"
        packageName: "auth"
        serviceName: "AuthService"
        useHTTPS: false

  - name: TeamMock
    handler:
      graphql:
        source: "./schemas/team.mock.graphql"
    transforms: []

  - name: TournamentMock
    handler:
      graphql:
        source: "./schemas/tournament.mock.graphql"
    transforms: []
  
  - name: Game
    handler:
      grpc:
        endpoint: localhost:50054
        protoFilePath: ./proto/game.proto

serve:
  port: 4000
  mock: true
