sources:

  - name: User
    handler:
      grpc:
        endpoint: localhost:30051
        source: "proto/user.proto"
        packageName: "user"
        serviceName: "UserService"
        useHTTPS: false
  - name: Auth
    handler:
      grpc:
        endpoint: localhost:30051
        source: "proto/auth.proto"
        packageName: "auth"
        serviceName: "AuthService"
        useHTTPS: false



  - name: Invitation
    handler:
      grpc:
        endpoint: "localhost:30052"
        source: "./proto/invitation.proto"
        packageName: "team"
        serviceName: "InvitationService"
        useHTTPS: false
  - name: TeamMember
    handler:
      grpc:
        endpoint: "localhost:30052"
        source: "./proto/team_member.proto"
        packageName: "team"
        serviceName: "TeamMemberService"
        useHTTPS: false
  - name: Team
    handler:
      grpc:
        endpoint: "localhost:30052"
        source: "./proto/team.proto"
        packageName: "team"
        serviceName: "TeamService"
        useHTTPS: false

  - name: MatchTeam
    handler:
      grpc:
        endpoint: "localhost:30053"
        source: "./proto/match_team.proto"
        packageName: "tournament"
        serviceName: "MatchTeamService"
        useHTTPS: false
    transforms:
      - namingConvention:
          mode: wrap
          namingConvention:
            typeNames: pascalCase
            fieldNames: snakeCase
            enumValues: upperCase
  - name: Match
    handler:
      grpc:
        endpoint: "localhost:30053"
        source: "./proto/match.proto"
        packageName: "tournament"
        serviceName: "MatchService"
        useHTTPS: false  
    transforms:
      - namingConvention:
          mode: wrap
          namingConvention:
            typeNames: pascalCase
            fieldNames: snakeCase
            enumValues: upperCase      
  - name: PlayerStats
    handler:
      grpc:
        endpoint: "localhost:30053"
        source: "./proto/player_stats.proto"
        packageName: "tournament"
        serviceName: "PlayerStatsService"
        useHTTPS: false
    transforms:
      - namingConvention:
          mode: wrap
          namingConvention:
            typeNames: pascalCase
            fieldNames: snakeCase
            enumValues: upperCase
  - name: TournamentTeam
    handler:
      grpc:
        endpoint: "localhost:30053"
        source: "./proto/tournament_team.proto"
        packageName: "tournament"
        serviceName: "TournamentTeamService"
        useHTTPS: false
    transforms:
      - namingConvention:
          mode: wrap
          namingConvention:
            typeNames: pascalCase
            fieldNames: snakeCase
            enumValues: upperCase
  - name: Tournament
    handler:
      grpc:
        endpoint: "localhost:30053"
        source: "./proto/tournament.proto"
        packageName: "tournament"
        serviceName: "TournamentService"
        useHTTPS: false
    transforms:
      - namingConvention:
          mode: wrap
          namingConvention:
            typeNames: pascalCase
            fieldNames: snakeCase
            enumValues: upperCase

  - name: Game
    handler:
      grpc:
        endpoint: localhost:30054
        source: "proto/game.proto"
        packageName: "game"
        serviceName: "GameService"
        useHTTPS: false

    transforms:
      - namingConvention:
          mode: wrap
          namingConvention:
            typeNames: pascalCase
            fieldNames: snakeCase
            enumValues: upperCase  

serve:
  port: 4000
